defaults: &defaults
  host: localhost
#  slave_one:
#    port: 27018
#  slave_two:
#    port: 27019

development:
  <<: *defaults
  database: otp_dev

test:
  <<: *defaults
  database: otp_test

production:
  <<: *defaults
  #host: db.mongohq.com
  #username: user
  #password: pass
  database: otp_pro